services:

  frontend:
    build: ./notes-React
    container_name: frontend
    expose:
      - "80"

  backend:
    build:
      context: ./notes-Spring
    container_name: backend
    expose:
      - "8080"
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notesdb
    ports:
    - "3306:3306"
    healthcheck:
       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
       interval: 10s
       retries: 5
    
    