version: "3"

services:
  frontend:
    build: ./notes-React
    container_name: frontend
    expose:
      - "80"

  backend:
    build: ./notes-Spring
    container_name: backend
    expose:
      - "8080"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend